version: "3.5"

services:
  healthchecks:
    image: healthchecks/healthchecks:${IMAGE_TAG:-latest}
    container_name: healthchecks
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      # Had to change owner of folder on host to ensure container could write database into it
      # sudo chown -R 999:999 /var/lib/docker/volumes/healthchecks/_data/
      -   healthchecks:/data
    env_file:
      - ../../stack.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.services.healthchecks.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.healthchecks.service=healthchecks"
      - "traefik.http.routers.healthchecks.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.healthchecks.entrypoints=${TRAEFIK_ROUTERS_ENTRYPOINTS}"
      - "traefik.http.routers.healthchecks.tls.certresolver=${TRAEFIK_ROUTERS_CERTRESOLVER}"

volumes:
  healthchecks:
    external: true

networks:
  default:
    external:
      name: ${NETWORK_NAME}

#Create database tables and a superuser account:
#cd ~/webapps/healthchecks
#./manage.py migrate
#./manage.py createsuperuser
