version: "3.5"

services:
  drone-server:
    image: drone/drone:${IMAGE_TAG:-latest}
    container_name: drone-server
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - "drone:/var/lib/drone/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ../../stack.env
    labels:
      - "diun.enable=true"

volumes:
  drone:
    external: true
