version: "3.5"

services:
  drone-runner:
    image: drone/drone-runner-docker:${IMAGE_TAG:-latest}
    container_name: drone-runner
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ../../stack.env
    labels:
      - "diun.enable=true"
