version: "3.5"

services:
  grafana:
    image: grafana/grafana:${IMAGE_TAG:-latest}
    container_name: grafana
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - grafana:/var/lib/grafana
    env_file:
      - ../../stack.env
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.rule=Host(`${GF_SERVER_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"

volumes:
  grafana:
    external: true

networks:
  default:
    external:
      name: ${NETWORK_NAME}
