version: "3.5"

services:
  influxdb:
    image: influxdb:${IMAGE_TAG:-alpine}
    container_name: influxdb
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - ../../stack.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.services.influxdb.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.routers.influxdb.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.influxdb.entrypoints=${TRAEFIK_ROUTERS_ENTRYPOINTS}"
      - "traefik.http.routers.influxdb.tls.certresolver=${TRAEFIK_ROUTERS_CERTRESOLVER}"
      - "traefik.http.routers.influxdb.middlewares=${known-ips}"

volumes:
  influxdb:
    external: true

networks:
  default:
    external:
      name: ${NETWORK_NAME}
